#<one line to give the program's name and a brief idea of what it does.>
#    Copyright (C) 2021 iWayVietnam  & Copyright (C) 2024 Platform Libre
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>
version: '3.2'
services:
  dns-server:
    image: 4km3/dnsmasq
    container_name: dns-server
    restart: always
    cap_add:
      - NET_ADMIN
    command: --address=/platformlibre.com/10.100.10.108 --domain=platformlibre.com --mx-host=platformlibre.com,mail.platformlibre.com,0
    network_mode: host
    
  zimbra_all:
    image: platformlibre/zimbra_all
    container_name: zimbra-server
    hostname: mail.platformlibre.com
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
    volumes:
      - './zimbra-storage:/opt/zimbra:rw'
    environment:
      - PASSWORD=${PASSWORD}
    network_mode: host
